### ISSUE TITLE
Comportement des args de echo  a revoir 

### ISSUE THREAD

**Issue by tmatis** [tmatis/minishell#6]
[tmatis@arch42 home]$ echo -n -n
[tmatis@arch42 home]$ echo -n -n -n 
[tmatis@arch42 home]$ echo -n -n -n -nn
[tmatis@arch42 home]$ echo -n -n -n -nnnn
[tmatis@arch42 home]$ echo -n -n -n -nnnn -nnnn
[tmatis@arch42 home]$ echo -n -n -n -nnnn -nnnnnnnnnnn
[tmatis@arch42 home]$ echo -n -n -n -nnnn -nnnnnnnnnnnm

**Comment by jmz-mzr** [comment]
close #6; Excellent!
